# Generated by Django 5.1 on 2024-11-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='Тема:')),
                ('article', models.TextField(verbose_name='Информация:')),
            ],
            options={
                'verbose_name': 'Информацию',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.CreateModel(
            name='Confidentiality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема:')),
                ('article', models.TextField(verbose_name='Информация:')),
            ],
            options={
                'verbose_name': 'политику конфеденциальности',
                'verbose_name_plural': 'Политика конфеденциальности',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес:')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон:')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail:')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='Тема:')),
                ('article', models.TextField(verbose_name='Информация:')),
            ],
            options={
                'verbose_name': 'оплату и услугу сервиса',
                'verbose_name_plural': 'Оплата и услуги сервиса',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название магазина')),
            ],
            options={
                'verbose_name': 'название',
                'verbose_name_plural': 'Название',
            },
        ),
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема:')),
                ('article', models.TextField(verbose_name='Информация:')),
            ],
            options={
                'verbose_name': 'интересный факт',
                'verbose_name_plural': 'Интересные факты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема:')),
                ('article', models.TextField(verbose_name='Информация:')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема:')),
                ('article', models.TextField(verbose_name='Информация:')),
            ],
            options={
                'verbose_name': 'офферту',
                'verbose_name_plural': 'Офферты',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема:')),
                ('article', models.TextField(verbose_name='Информация:')),
            ],
            options={
                'verbose_name': 'акцию',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
